### ISSUE TITLE
System Events Error

### ISSUE THREAD

**Issue by karlilarsen** [brandonusher/Apple-ID-AppleScript#40] opened 2015-12-08 02:04 UTC
I'm getting this error after clicking on iBooks, it won't get past the "Create Apple ID" button, and keeps going back to the Apple Logo. Any thoughts?

error "System Events got an error: Can’t get scroll area 1 of window 1 of application process \"iTunes\". Invalid index." number -1719 from scroll area 1 of window 1 of application process "iTunes"

**Comment by brandonusher** [comment] 2015-12-08 05:24
Duplicate of #39

**Closed by brandonusher** 2015-12-08 05:24 UTC
Labels: duplicate
