### ISSUE TITLE
iTunes 12.3.1.23 error

### ISSUE THREAD

**Issue by kdglover9** [brandonusher/Apple-ID-AppleScript#36] opened 2015-10-30 19:09 UTC
Error:
error "System Events got an error: Can’t get UI element \"Welcome to the iTunes Store\" of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process \"iTunes\"." number -1728 from UI element "Welcome to the iTunes Store" of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process "iTunes"

NOTES:
Once you click on the iTunes window it refreshes and loads the [UI element \"Welcome to the iTunes Store\"]. Tried increasing the wait / repeat counts, iTunes only refreshes to that window once the cursor moves or clicks. I did successfully time it once and get it to refresh without interrupting the script. Completed successfully without intervention after that point.

**Comment by brandonusher** [comment] 2015-10-30 20:12
Duplicate of #33

**Closed by brandonusher** 2015-10-30 20:12 UTC
Labels: duplicate
