### ISSUE TITLE
Please answer ! problem with El Capitan

### ISSUE THREAD

**Issue by khazaee** [brandonusher/Apple-ID-AppleScript#42] opened 2015-12-22 23:02 UTC
Script Error: System Events got an error: Can’t get scroll area 1 of window 1 of application process "iTunes". Invalid index.

**Comment by brandonusher** [comment] 2015-12-22 23:38
Duplicate of #30 just like your last one. I'm still searching for an answer for this but seeing as it's holiday time, I don't have much time to dedicated to tracking down this issue.

**Closed by brandonusher** 2015-12-22 23:38 UTC
Labels: duplicate

**Comment by khazaee** [comment] 2015-12-22 23:40
:(

**Comment by seesolve** [comment] 2016-09-21 05:07
The reference to the element has changed. Use the following line instead.
```
click button "Create New Apple ID"  of window "iTunes" 
```
